### ISSUE TITLE
C sharp version

### ISSUE THREAD

**Issue by voviks21** [byronknoll/visibility-polygon-js#4]
Hi Byron! 
Can this library be translated to C# language? 
Or maybe there is C# version exists?
*thanks*

**Comment by xaviergonz** [comment]
https://github.com/xaviergonz/visibility-polygon-csharp

**Comment by xaviergonz** [comment]
Or if you prefer a nuget package then https://www.nuget.org/packages/VisibilityPolygonCSharp/
