### ISSUE TITLE
Possible to get the invisibility polygon, so the negative or opposite polygon?

### ISSUE THREAD

**Issue by BdR76** [byronknoll/visibility-polygon-js#6]
Is it possible to get the invisibility polygon? This could be used as a way to block invisible parts in a game, see [this forum post](https://phaser.discourse.group/t/phaser-line-of-sight-polygon-and-the-negative-invisible-polygon/7187)

Theoretically it is possible to draw a "negative" polygon and have it be one single polygon by using the edges of the viewport to connect any seperate parts. So this can result in infinitely thin lines along the viewport edges but that's ok.

Any ideas on how to make such an algorithm?

**Comment by byronknoll** [comment]
One idea is to use some separate geometry library, which supports something like polygon subtraction (viewport - visibility polygon).

Another idea is to write some custom code: I guess you already have all the necessary vertices of the polygon (the union of points in the viewport and the visibility polygon), so you just need to somehow iterate through them in the right order to define your polygon.

Note: I am not actively working on this library anymore, so won't be adding any new features.
