### ISSUE TITLE
Cone shaped visibility

### ISSUE THREAD

**Issue by chazapp** [byronknoll/visibility-polygon-js#8]
Hi, thanks a lot for the code, i'm using it in my Phaser 3 project. You can test it [here](https://mtvs.chaz.pro) (beware, might be gpu intensive).   
I would like to adapt this code to the game by making the player's visibility as a cone in front of the player. Given the player's rotation in deg/rad and a constant F field of view, how could we adapt the code so that the `compute` method does return only the rays in front of the player and not the whole 360° ?  
Thanks a lot again !

**Comment by byronknoll** [comment]
Would it work to create two additional walls, which move around based on where the player is facing? The player could be in the corner of those two walls, which would block everything behind.

**Comment by chazapp** [comment]
That's actually a really clever trick i hadn't thought of. I just need to find out how to place these walls, which should be quite easier than figuring out the maths needed to make the cone. Thanks a lot for this idea !
